---
title: 'SDS-192: Mini-Project #02'
author: "Sarah Elghazoly, Abby Doctor"
date: "3/10/2017"
output: html_document
---
##Loading the files
```{r}
library(dplyr)
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
library(ggplot2)
```
```{r}

```

##Maybe what percentage of incumbents win a second election? Does that vary by state

```{r}
g1 <- house_elections %>% filter(ge_winner == "W") %>% group_by(incumbent)%>% group_by(state)
ggplot(g1, aes(x = state)) +geom_bar(aes(fill = incumbent))
```

##Margin of Victory: House Elections Margin of Victory, combine with amount of contribution to candidate
So far I have total transaction amounts by party (how to divide by years?)
```{r}
f2 <- contributions %>% inner_join(candidates, by = "cand_id", na.rm = FALSE) %>% filter(state == "NY") %>% arrange(by = cand_party_affiliation)

ggplot(f2, aes(x= cand_election_yr, y = sum(transaction_amt)))+geom_bar(stat = "identity", aes(color = cand_party_affiliation))

```

##Making a Big Data Collection house_elections, candidates
```{r}
candidates <- rename(candidates, c("cand_state" = "state", "cand_name" = "candidate_name", "cand_election_yr" = "year"))
house_elections <- house_elections %>% mutate_each(funs(toupper)) house_elections$general_votes <- as.numeric(house_elections$general_votes)
cand_elections <- candidates %>% inner_join(house_elections, by  = c("candidate_name", "state"), na.rm = FALSE)
cand_elections <- cand_elections %>% select(candidate_name, year, state, incumbent, party, general_votes, ge_winner, cand_office)
```


##Choosing an office
```{r}
house_values <- cand_elections %>% 
  filter(cand_office == "H") %>%
  arrange(by = party)
house_values

ggplot(house_values, aes(x = state, y = general_votes)) + geom_bar(stat = "identity", aes(fill = party))
```

